# Imagem base
FROM node:18

# Criar diretório de trabalho
WORKDIR /app

# Copiar package.json
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante do código
COPY . .

# Expor a porta do backend
EXPOSE 5000

# Rodar o servidor
CMD ["npm", "start"]
